### ISSUE TITLE
formdata.EquipmentFormData へのValidation定義

### ISSUE THREAD

**Issue by te170476** [Y-kwhrt/TeamStupidUnion#12]
Validation内容の検討もしないといけない

**Comment by 170154** [comment]
yaruo-

**Comment by 170154** [comment]
madadayo-

**Comment by 170154** [comment]
#12 を書きました
コミットメッセージ書き忘れたのでここに書きます。
nullの拒否、空白の拒否の実装
耐用年数の０以下の数値の除外、小数を許容しない処理を書きました。
小数を許容しない処理を実装するにあたり、
EquipmentFormDataのlifespanInYearsをint型からstring型に変更しました。
注意喚起：beanとformDataで型が違うため、どっかしらでエラーが発生する可能性があります
