### ISSUE TITLE
データベースを導入する

### ISSUE THREAD

**Issue by te170476** [Y-kwhrt/TeamStupidUnion#20]
MySQLを本番環境に対して導入する。
H2データベースをテスト環境限定にして導入する。

#### できたらやりたい
- テーブル作成の自動化

**Comment by Y-kwhrt** [comment]
とりあえずテスト環境下での導入を実施してみる

**Comment by te170476** [comment]
本番環境にMySQLを導入するのが本筋から外れる割に手間そうなので、とりあえずテスト環境下に明示的にH2DBを入れるのだけしておくことになりました。
