### ISSUE TITLE
Equipment listの各要素に属性付与

### ISSUE THREAD

**Issue by te170476** [Y-kwhrt/TeamStupidUnion#23]
`list.html` 内のリスト表示部分を
```
<span class="equipment-lifespanInYears">ノートPC</span>
```
みたいに変更する。

```
.getElementsByClassName("equipment-lifespanInYears")
// このあと .tagname == "SPAN" する
```
で取得できるようにする。

**Comment by Y-kwhrt** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/53cfeb60-1b0f-4e50-bb3b-c7e2bb5a7824?env_id=ibm:yp:us-south "simple-toolchain-20200727042844717"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/5ec2321c-6ae0-4e90-be4d-2d786eafc966 "simple-toolchain-20200727042844717") deployed [TeamStupidUnion](https://github.com/Y-kwhrt/TeamStupidUnion/releases/tag/deploy-ibm-yp-us-south-3tyo.eye.tama-gmail.com-dev-20200908-044506 "deploy-ibm-yp-us-south-3tyo.eye.tama-gmail.com-dev-20200908-044506") to [dev](https://console.bluemix.net/apps/3f8e5b8b-cd92-4c3e-a591-7b21d8a846c1?env_id=ibm:yp:us-south "ibm:yp:us-south:3tyo.eye.tama@gmail.com:dev"), including commit 6a93ae83135fca0f204e70cdc7fc3b5286dc5817
