### ISSUE TITLE
エラーメッセージが文字化けする

### ISSUE THREAD

**Issue by te170476** [Y-kwhrt/TeamStupidUnion#26]
`ValidationMessages.properties` が文字化けする。
### 対処法
- 文字コードを `ISO/IEC 8859-1` に変更する
- `UTF-8` を読み込めるようにする  
Java 9に上げる  
↑ [Java9でResourceBundle のデフォルト文字コードが UTF-8に](http://yanok.net/2017/07/java-9-resourcebundle-utf-8.html)  
ロード時の処理を変更してUTF-8に対応する  
↑ [読み込み文字コード変更](http://blog.k11i.biz/2014/09/java-utf-8.html),  
↑ [propertiesの読み込み処理を上書き](https://qiita.com/NagaokaKenichi/items/65d0e07151292968d67f)

**Comment by Y-kwhrt** [comment]
https://qiita.com/inuDrill/items/a0c8ab8a8ba62e7e66c1
propertiesに日本語でエラー書いてこんな感じになれば正常とのこと

**Comment by Y-kwhrt** [comment]
今のissue-26ブランチのpropertiesなら文字化けしないかも

**Comment by te170476** [comment]
文字化け対策という名のJavaバージョンアップに成功し舞田

`IBM Cloud/Cloud Foundry/Java Buildpack` において、ビルド結果を実行するJREのバージョンがデフォルトで java8 になっており、これのバージョンを指定するために #34 の 変更が必要でした。なんでや！！！！！！！！！！！！！！！！！！！
