### ISSUE TITLE
テストを書きやすくする

### ISSUE THREAD

**Issue by te170476** [Y-kwhrt/TeamStupidUnion#40]
InputFormとか、クラス化しておきたいなって思いました。

**Comment by Y-kwhrt** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/53cfeb60-1b0f-4e50-bb3b-c7e2bb5a7824?env_id=ibm:yp:us-south "simple-toolchain-20200727042844717"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/5ec2321c-6ae0-4e90-be4d-2d786eafc966 "simple-toolchain-20200727042844717") deployed [TeamStupidUnion](https://github.com/Y-kwhrt/TeamStupidUnion/releases/tag/deploy-ibm-yp-us-south-3tyo.eye.tama-gmail.com-dev-20200930-060614 "deploy-ibm-yp-us-south-3tyo.eye.tama-gmail.com-dev-20200930-060614") to [dev](https://console.bluemix.net/apps/3f8e5b8b-cd92-4c3e-a591-7b21d8a846c1?env_id=ibm:yp:us-south "ibm:yp:us-south:3tyo.eye.tama@gmail.com:dev"), including commit 0347e9ab07c915119d06b1bf6990ce2e0f495674
